name: Drupal Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@master
      with:
              dockerfile: "Dockerfile"
              config: ./hadolint.yaml

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
